// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgpqyltisvahrekcgofk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncHF5bHRpc3ZhaHJla2Nnb2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTA1NTEsImV4cCI6MjA2MTg4NjU1MX0.H_DDj8t7pcCl4tosgZ25NzPE-RfYcvO0CDROU631F2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);